# Generated by Django 2.1.1 on 2018-09-23 01:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('baby_date_of_birth', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('details', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agency')),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name', 'date_of_birth', 'baby_date_of_birth'], name='api_client_name_8b2a0d_idx'),
        ),
    ]
